### PR TITLE
Urleaka tuples

### PR DESCRIPTION
**Pull request by taylorperkins**

### CODE REVIEW

**Comment by taylorperkins** [comment]
Hey @unewsome ! Great work on this :) I especially like that you thought about including sections for mutability, memory, and execution time differences. I'll make a couple suggestions

* I think the `Execution Time` piece has your output in this branch.. This can be easily fixed by running the notebook, going to the `Cell` tab (right next to Insert and Kernel), going to `All Output`, then clicking the `Clear` option.
* For the mutability, memory, and execution time pieces, can we include a short description on what each of those terms mean, why they could be important, and what we are expecting in the output before the cell is run? For example, something like: 
```
## Mutability
--- Talk about difference between mutable and immutable objects ---
--- Why can't I change a value in a tuple --- 
--- Whats a way that I can change the value in a tuple ---
etc
```
* Could we add a blank cell underneath the `value in tuple syntax` piece as well as the `unpacking` piece so we could add a "Your turn" section? 
* And lastly.. Regarding the Tuple operations part. I like including the `del`, `len` pieces! However, I don't think saying `Tuples don't have many methods that can be used.` is appropriate. They have 2! One of them you showed off earlier in the lesson :) 
    * `index` - returns the index of a value
    * `count` - counts the number of times an item shows up in a tuple
We don't have to talk about those if you don't feel it's necessary, but it could be good to change the wording. 


Otherwise, great job! I appreciate the thought you put into this lesson :)

**Comment by unewsome** [comment]
@taylorperkins Thanks for the solid comments.  If you think the for loop is ok to use to describe the execution time difference I will keep it, but I couldn't understand why it kept repeating the iteration once it got to 9...

**Comment by taylorperkins** [comment]
I think it's because you're running the test 100 times

**Comment by unewsome** [comment]
yeah ... I think so too

Do I need to make a new pull request

**Comment by taylorperkins** [comment]
This looks great UrLeaka! Nice job :D

**Pull request merged**
