### PR TITLE
Data analytics revamp

### PR DESCRIPTION
**Pull request by taylorperkins**
# Data Analytics Revamp!

Ok, a lot of stuff going on here. 
This is my initial take at creating a "python orientation" geared towards the data analytics (or data science) students.

Essentially, it is the frankenstein child of `nashville-software-school/bangazon-llc`, but only keeping the python stuff. 

## Structure
This repo is broken into 2 parts: `chapters` and `practice`.
The general idea is to go through _all_ of the chapters in class. 
Instructors and students walk through these chapters together, fill in the blanks, do some of the code, and talk about all the concepts. 
I estimate this to take 2 days!

Once all of the chapters are completed, the students can go through the practice notebooks.
There is an order to the notebooks based on difficulty.. 
Some are marked as advanced.
For the most part, these are exercises that are copy/pasted from the web-dev cohort.
I think these are all pretty great exercises, but it could be good to consider coming up with a couple others.. 
Specifically around creating functions that could serve as functions to be used in `DataFrame.series.apply(func)`.

## Chapters
I tried to keep a standard structure to all of the chapters. 
For the most part, the flow goes like this: 

```
# Concept
Go over a concept

## Example
Give an example

## Your Turn
Students code out the concept on their own

..rinse and repeat..
```

A couple differences between the web-dev and this: 
* I put the for-loops at the end. Idea being.. You can't loop until you know what you can loop over!
* Intro chapter is all about basic python types (str, int, float, boolean)
* Took out quite a few chapters - Any sort of IDE references, Debugging in VSCode, Custom Types with Classes, Student exercises (main focus was on OOP), Class Properties, Try/Catch and Exceptions, Python Packages, Inheritance, Multiple Inheritance, and Decorators

I think that we could still consider `Python Packages` as well as `Try/Catch and Exceptions` to be chapters in this orientation.
Took them out for now as a test drive.

Also thought about keeping all of the other chapters that I removed, but in a completely separate folder that we don't go over at all. 
Like an `above-and-beyond` folder / easter egg that the students can find and explore on their own.

## Practice
Like I said, basically copy/pasted from the web-dev.
Each practice/challenge is split into separate notebooks.

I am still pondering the orders.

## RUNNING THIS LOCALLY

Please do this!

* Clone down the repo
* Check out the branch
```
git fetch --all && git checkout data-analytics-revamp
```
* Then, follow the instructions in the README, starting with the INSTALLATIONS.

Nothing about this orientation requires any other packages other than what's included in the standard library.
You should be able to run everything AS IS.

I would _really appreciate_ feedback on the instructions, chapters, and practice exercises. 

Things to think about: 
* Does the wording here make sense?
* Correct grammar?
* Are the concepts explained well?
* Do the coding sections help "lock-in" the concepts?
* Is anything out of order?

If you have suggestions, please tell me in this pull request, or suggest a change in a new branch/pr!
Would love any and all input.

### CODE REVIEW

**Comment by MaryLvV** [comment]
Chapter1 - Intro Notebook
- would it make sense to print out the types after they create variables for verification/reinforcement?
Screen Shot 2020-03-15 at 1 14 15 PM
- In the `Note` under Order of Operations, do you mean to say `** represents exponent`
- clarify that `strip` method removes leading and trailing whitespace from a string (also maybe a better example to show this)

**Comment by MaryLvV** [comment]
Chapter 2 - Conditionals Notebook
- typo:  Wen a number is greater than 20 --> When a number is greater than 20

**Comment by MaryLvV** [comment]
Chapter 3 - Lists Notebook 
- typo: it's indices --> its indices

- typo: WOAH --> WHOA  :)

- you don't explicitly talk about negative index but it feels like there's a place to talk about and explore (Is there another way?)...right?

**Comment by MaryLvV** [comment]
Chapter 4 - Dictionaries
This looks great.

**Comment by MaryLvV** [comment]
Chapter 5 - Tuples Notebook
- typo: parenthesis --> parentheses

- Is it worth pointing out that comma separated items (without parentheses) are tuples too? I added a couple cells to show that, but feel free to ignore/remove if you think it's not important to point out here

**Comment by MaryLvV** [comment]
Chapter 6 - Sets Notebook
- "Developers use" --> "You can use"

- typo: to see if two, or more --> to see if two or more

-  "Notice that both of those sets were" --> "Notice that in the second example the set was"

**Comment by MaryLvV** [comment]
Chapter 7 - Loopin it Notebook

- "I'm a real developer" --> "I'm a real data analyst"

- typo: tobecome --> to become

**Comment by MaryLvV** [comment]
Chapter 8 - Functions Notebook
a couple of little edits to the `Breaking it down` section

**Comment by taylorperkins** [comment]
> Chapter 3 - Lists Notebook
> ...
> * you don't explicitly talk about negative index but it feels like there's a place to talk about and explore (Is there another way?)...right?

I'll work on getting a piece about this in there as well :) Thank you!

**Pull request merged**
